'use client'
import { FormEvent, useState } from 'react'
type Content = { id: string; type: string; title: string; status: string }
type Request = { id: string; contentTitle: string; kind: string; statut: string; message: string; response: string | null; createdAt: string }
export default function EditorialRequestsPanel({ contents, initialRequests }: { contents: Content[]; initialRequests: Request[] }) {
  const [requests, setRequests] = useState(initialRequests); const [contentKey, setContentKey] = useState(''); const [kind, setKind] = useState('QUESTION'); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false)
  async function submit(event: FormEvent) { event.preventDefault(); const content = contents.find((item) => `${item.type}:${item.id}` === contentKey); if (!content) return; setLoading(true); setError(''); const response = await fetch('/api/editorial-requests', { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({ contentType:content.type, contentId:content.id, kind, message }) }); const data = await response.json(); if (!response.ok) setError(data.error || 'Erreur'); else { setRequests((current) => [{ id:data.id, contentTitle:content.title, kind, statut:'EN_ATTENTE', message, response:null, createdAt:new Date().toISOString() }, ...current]); setMessage(''); setContentKey('') } setLoading(false) }
  return <section className="card p-5 lg:col-span-2"><h2 className="font-display font-semibold text-nihary-ambre-fonce">Échanges avec le comité éditorial</h2><p className="text-xs text-nihary-gris mt-1 mb-4">Une soumission envoyée est verrouillée. Utilisez cet espace pour poser une question ou demander officiellement son retrait.</p><form onSubmit={submit} className="grid md:grid-cols-[1fr_180px] gap-3"><select className="input" required value={contentKey} onChange={(e)=>setContentKey(e.target.value)}><option value="">Choisir une soumission</option>{contents.map((item)=><option key={`${item.type}:${item.id}`} value={`${item.type}:${item.id}`}>{item.title} — {item.status}</option>)}</select><select className="input" value={kind} onChange={(e)=>setKind(e.target.value)}><option value="QUESTION">Question éditoriale</option><option value="RETRAIT">Demande de retrait</option></select><textarea className="input md:col-span-2 min-h-24" required value={message} onChange={(e)=>setMessage(e.target.value)} placeholder="Expliquez précisément votre demande…"/><div>{error && <p className="text-sm text-red-700">{error}</p>}</div><button className="btn-primary justify-self-end" disabled={loading}>{loading?'Envoi…':'Envoyer au comité'}</button></form>{requests.length>0&&<div className="mt-6 border-t pt-4 space-y-3">{requests.map((request)=><div key={request.id} className="bg-nihary-sable/50 rounded p-3 text-sm"><div className="flex justify-between gap-3"><strong>{request.contentTitle}</strong><span className="badge">{request.statut}</span></div><p className="text-nihary-gris mt-1">{request.kind} · {request.message}</p>{request.response&&<p className="mt-2 border-l-2 border-nihary-or pl-3"><strong>Réponse :</strong> {request.response}</p>}</div>)}</div>}</section>
}
