import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { auth } from "@/lib/auth/config";
import { hasPermission } from "@/lib/auth/permissions";
import { cleanString, isRecord } from "@/lib/api-validation";
import { slugifyUnique } from "@/lib/slugify";

async function allowed(){const session=await auth();if(!session?.user?.id||!await hasPermission(session.user.id,"MANAGE_OFFERS"))return null;return session}
export async function GET(){if(!await allowed())return NextResponse.json({error:"Accès refusé"},{status:403});return NextResponse.json({items:await prisma.opportunity.findMany({orderBy:{updatedAt:"desc"}})})}
export async function POST(request:NextRequest){const session=await allowed();if(!session?.user?.id)return NextResponse.json({error:"Accès refusé"},{status:403});try{const body:unknown=await request.json();if(!isRecord(body))return NextResponse.json({error:"Requête invalide"},{status:400});const titre=cleanString(body.titre,240),organisation=cleanString(body.organisation,200),type=cleanString(body.type,40),resume=cleanString(body.resume,800),description=cleanString(body.description,10000);if(!titre||!organisation||!type||!resume||!description)return NextResponse.json({error:"Titre, organisation, type, résumé et description sont requis"},{status:400});const payload={domaine:cleanString(body.domaine,120)||"N/A",lieu:cleanString(body.lieu,160)||"N/A",mode:cleanString(body.mode,40)||"N/A",dateLimite:cleanString(body.dateLimite,30)||"N/A",image:cleanString(body.image,500)||"/uploads/magazine/magazine-economie-informelle.jpg",resume,description,contrat:cleanString(body.contrat,100)||"N/A",remuneration:cleanString(body.remuneration,160)||"N/A",contact:cleanString(body.contact,200)||"N/A"};const item=await prisma.opportunity.create({data:{slug:slugifyUnique(titre),titre,organisation,type,statut:body.statut==="PUBLIE"?"PUBLIE":"BROUILLON",payload,createdById:session.user.id}});return NextResponse.json({success:true,item},{status:201})}catch(error){console.error("POST /api/admin/offres",error);return NextResponse.json({error:"Création impossible"},{status:500})}}
export async function PATCH(request:NextRequest){if(!await allowed())return NextResponse.json({error:"Accès refusé"},{status:403});try{const body:unknown=await request.json();if(!isRecord(body)||typeof body.id!=="string")return NextResponse.json({error:"Requête invalide"},{status:400});const current=await prisma.opportunity.findUnique({where:{id:body.id}});if(!current)return NextResponse.json({error:"Offre introuvable"},{status:404});const payload=isRecord(current.payload)?{...current.payload}:{};for(const key of ["domaine","lieu","mode","dateLimite","image","resume","description","contrat","remuneration","contact"]){if(typeof body[key]==="string")payload[key]=cleanString(body[key],key==="description"?10000:800)||"N/A"}const item=await prisma.opportunity.update({where:{id:body.id},data:{...(typeof body.titre==="string"?{titre:cleanString(body.titre,240)}:{}),...(typeof body.organisation==="string"?{organisation:cleanString(body.organisation,200)}:{}),...(typeof body.type==="string"?{type:cleanString(body.type,40)}:{}),...(body.statut==="PUBLIE"||body.statut==="BROUILLON"||body.statut==="ARCHIVE"?{statut:body.statut}:{}),payload}});return NextResponse.json({success:true,item})}catch(error){console.error("PATCH /api/admin/offres",error);return NextResponse.json({error:"Mise à jour impossible"},{status:500})}}
