/**
 * Seed 01 — Revue scientifique (Pilier 1)
 * 9 articles peer-reviewed publiés + 2 en attente de modération.
 */
import { prisma, slugify } from "./_client";

export async function seedRevue(auteurIds: Record<string, string>) {
  console.log("📰 Création des articles de la Revue...");

  const articles = [
    {
      titre: "Transformations du marché du travail informel à Antananarivo : une approche par les trajectoires individuelles",
      resume: "Cet article analyse les mutations récentes du secteur informel dans la capitale malgache à partir d'une enquête longitudinale menée auprès de 200 travailleurs informels entre 2019 et 2023. En mobilisant la sociologie des parcours de vie, nous montrons comment la pandémie de Covid-19 a accéléré des dynamiques de précarisation déjà à l'œuvre, tout en révélant des stratégies de résilience spécifiques aux contextes urbains d'Afrique subsaharienne.",
      motsClés: ["travail informel", "Antananarivo", "précarité", "Covid-19", "trajectoires"],
      discipline: "SOCIOLOGIE",
      langue: "FR",
      accesLibre: true,
      statut: "PUBLIE",
      vues: 312,
      telechargements: 87,
      volume: 1,
      numero: 1,
      pages: "1-24",
      fichierUrl: "/uploads/articles-pdf/article-marche-travail-informel.pdf",
      auteurEmail: "jean.rakoto@univ-tana.mg",
    },
    {
      titre: "Archives coloniales et mémoire populaire : la construction narrative de la résistance Menalamba à Madagascar (1895-1897)",
      resume: "À partir d'un croisement entre archives coloniales françaises et sources orales collectées dans les hautes terres malgaches, cet article revisite l'insurrection Menalamba. Nous montrons que la mémoire collective locale construit une représentation de cet épisode largement en décalage avec le récit colonial, révélant ainsi les enjeux identitaires et politiques d'une mémoire vivante.",
      motsClés: ["Menalamba", "colonisation", "archives", "mémoire", "Madagascar", "résistance"],
      discipline: "HISTOIRE",
      langue: "FR",
      accesLibre: true,
      statut: "PUBLIE",
      vues: 485,
      telechargements: 134,
      volume: 1,
      numero: 1,
      pages: "25-48",
      fichierUrl: "/uploads/articles-pdf/article-archives-coloniales-menalamba.pdf",
      auteurEmail: "hanta.razafy@ihm.mg",
    },
    {
      titre: "Pauvreté multidimensionnelle et capabilités en zone rurale malgache : au-delà du revenu monétaire",
      resume: "En appliquant l'approche par les capabilités d'Amartya Sen à un panel de 1 200 ménages ruraux malgaches (2018-2022), cet article propose un indice composite de bien-être qui dépasse les mesures monétaires classiques. Les résultats montrent que des régions classées pauvres selon le critère revenu présentent des niveaux de liberté substantielle significativement supérieurs à la moyenne nationale.",
      motsClés: ["capabilités", "pauvreté", "Madagascar", "Amartya Sen", "indice composite"],
      discipline: "ECONOMIE",
      langue: "FR",
      accesLibre: false,
      statut: "PUBLIE",
      vues: 267,
      telechargements: 52,
      volume: 1,
      numero: 1,
      pages: "49-72",
      fichierUrl: "/uploads/articles-pdf/article-pauvrete-capabilites.pdf",
      auteurEmail: "fidy.andriantsoa@ird.mg",
    },
    {
      titre: "Le dina comme institution de gouvernance foncière : droit coutumier et État dans les zones forestières du Menabe",
      resume: "Le dina, contrat social malgache de régulation communautaire, constitue une institution de gouvernance foncière parallèle aux structures étatiques dans les zones forestières du Menabe. Cet article, fondé sur 18 mois d'observation participante, analyse les mécanismes par lesquels le dina s'articule avec les dispositifs légaux nationaux et les politiques de conservation internationale.",
      motsClés: ["dina", "foncier", "gouvernance", "Menabe", "conservation", "coutume"],
      discipline: "ANTHROPOLOGIE",
      langue: "FR",
      accesLibre: true,
      statut: "PUBLIE",
      vues: 201,
      telechargements: 63,
      volume: 1,
      numero: 2,
      pages: "1-26",
      fichierUrl: "/uploads/articles-pdf/article-dina-foncier-menabe.pdf",
      auteurEmail: "voahirana.rakotondrabe@cnre.mg",
    },
    {
      titre: "Transition démocratique à Madagascar : les élections de 2023 entre institutionnalisation et persistance des logiques clientélistes",
      resume: "Cet article analyse les élections présidentielle et législatives malgaches de 2023 sous l'angle de la consolidation démocratique. Croisant analyse de données électorales et entretiens avec des acteurs politiques locaux, nous montrons la coexistence paradoxale d'une infrastructure institutionnelle formelle progressivement consolidée et de pratiques clientélistes structurelles qui limitent la représentativité du système.",
      motsClés: ["démocratie", "élections", "Madagascar", "clientélisme", "consolidation"],
      discipline: "SCIENCE_POLITIQUE",
      langue: "FR",
      accesLibre: true,
      statut: "PUBLIE",
      vues: 389,
      telechargements: 98,
      volume: 1,
      numero: 2,
      pages: "27-52",
      fichierUrl: "/uploads/articles-pdf/article-democratie-madagascar-2023.pdf",
      auteurEmail: "eric.ramaroson@sciencespo-mg.mg",
    },
    {
      titre: "Bilinguisme et construction identitaire chez les élèves du secondaire à Antananarivo",
      resume: "À partir d'une enquête sociolinguistique conduite dans huit établissements secondaires de la capitale, cet article explore les représentations que les élèves ont de leurs deux langues de scolarisation — le malgache et le français. Les résultats révèlent une tension entre une valorisation instrumentale du français et une identification affective forte au malgache, avec des variations significatives selon le milieu socio-économique.",
      motsClés: ["bilinguisme", "identité", "secondaire", "Antananarivo", "sociolinguistique"],
      discipline: "LINGUISTIQUE",
      langue: "FR",
      accesLibre: true,
      statut: "PUBLIE",
      vues: 178,
      telechargements: 41,
      volume: 1,
      numero: 2,
      pages: "53-76",
      fichierUrl: "/uploads/articles-pdf/article-bilinguisme-antananarivo.pdf",
      auteurEmail: "celestine.ramanantsoa@ulm.mg",
    },
    {
      titre: "Famadihana et modernité : recomposition des rites funéraires malgaches en contexte urbain",
      resume: "Le famadihana, rituel du retournement des morts, fait l'objet de recompositions profondes dans les espaces urbains d'Antananarivo. Cet article analyse, à partir d'une enquête ethnographique de deux ans, comment les contraintes économiques, les migrations et la diversification religieuse modifient les formes et les significations de ce rituel central de la société malgache.",
      motsClés: ["famadihana", "rites", "urbanisation", "religion", "Madagascar"],
      discipline: "ANTHROPOLOGIE",
      langue: "FR",
      accesLibre: true,
      statut: "PUBLIE",
      vues: 542,
      telechargements: 156,
      volume: 2,
      numero: 1,
      pages: "1-28",
      fichierUrl: "/uploads/articles-pdf/article-famadihana-modernite.pdf",
      auteurEmail: "voahirana.rakotondrabe@cnre.mg",
    },
    {
      titre: "Les stratégies éducatives des ménages défavorisés de Fianarantsoa : entre contraintes économiques et aspirations scolaires",
      resume: "Cet article examine, à partir d'une étude de cas approfondie conduite à Fianarantsoa, les stratégies éducatives des ménages à faibles revenus. En articulant sociologie de l'éducation et économie du ménage, nous montrons comment les familles arbitrent entre scolarisation des enfants, travail domestique et pression économique immédiate, et comment ces arbitrages reproduisent ou non les inégalités intergénérationnelles.",
      motsClés: ["éducation", "pauvreté", "Fianarantsoa", "stratégies familiales", "inégalités"],
      discipline: "SCIENCES_EDUCATION",
      langue: "FR",
      accesLibre: false,
      statut: "PUBLIE",
      vues: 223,
      telechargements: 67,
      volume: 2,
      numero: 1,
      pages: "29-54",
      fichierUrl: "/uploads/articles-pdf/article-strategies-educatives-fianarantsoa.pdf",
      auteurEmail: "celestine.ramanantsoa@ulm.mg",
    },
    {
      titre: "Genre et accès aux ressources naturelles dans les communautés paysannes du lac Alaotra",
      resume: "Cette recherche analyse les inégalités de genre dans l'accès et le contrôle des ressources naturelles — eau, terre, forêt — dans les communautés rurales riveraines du lac Alaotra. À partir d'une enquête mixte (questionnaires et entretiens semi-directifs), elle révèle que les femmes, bien que principales usagères des ressources, sont systématiquement exclues des instances de décision locales sur leur gestion.",
      motsClés: ["genre", "ressources naturelles", "Alaotra", "inégalités", "gouvernance"],
      discipline: "ETUDES_GENRE",
      langue: "FR",
      accesLibre: true,
      statut: "PUBLIE",
      vues: 297,
      telechargements: 88,
      volume: 2,
      numero: 1,
      pages: "55-78",
      fichierUrl: "/uploads/articles-pdf/article-genre-ressources-alaotra.pdf",
      auteurEmail: "hanta.razafy@ihm.mg",
    },
    // En attente
    {
      titre: "Reconfigurations identitaires des entrepreneurs malgaches de la diaspora en France",
      resume: "À partir d'entretiens biographiques menés auprès d'entrepreneurs malgaches installés en France métropolitaine, cet article examine comment se reconfigurent les identités professionnelles et nationales dans un contexte migratoire. Il met en lumière le rôle des associations de la diaspora comme espaces de négociation identitaire.",
      motsClés: ["diaspora", "identité", "entrepreneuriat", "migration", "France"],
      discipline: "SOCIOLOGIE",
      langue: "FR",
      accesLibre: false,
      statut: "EN_ATTENTE",
      vues: 0,
      telechargements: 0,
      auteurEmail: "jean.rakoto@univ-tana.mg",
    },
    {
      titre: "Droit foncier moderne et droit coutumier à Madagascar : complémentarité ou concurrence ?",
      resume: "Cet article propose une analyse comparée des régimes juridiques applicables au foncier rural à Madagascar, en mettant en regard la législation nationale issue des réformes de 2005-2007 et les normes coutumières locales. Il s'interroge sur les conditions d'une cohabitation productive entre ces deux ordres juridiques.",
      motsClés: ["foncier", "droit coutumier", "droit positif", "Madagascar", "réforme"],
      discipline: "DROIT",
      langue: "FR",
      accesLibre: true,
      statut: "EN_ATTENTE",
      vues: 0,
      telechargements: 0,
      auteurEmail: "fidy.andriantsoa@ird.mg",
    },
  ];

  let count = 0;
  for (const a of articles) {
    const auteurId = auteurIds[a.auteurEmail];
    if (!auteurId) continue;
    const slug = slugify(a.titre);
    await prisma.articleRevue.upsert({
      where: { doi: `10.1234/nihary.${slug.slice(0, 30)}` },
      update: { fichierUrl: (a as any).fichierUrl ?? null },
      create: {
        titre: a.titre,
        resume: a.resume,
        motsClés: a.motsClés,
        discipline: a.discipline as any,
        langue: a.langue as any,
        accesLibre: a.accesLibre,
        statut: a.statut as any,
        vues: a.vues,
        telechargements: a.telechargements,
        volume: (a as any).volume ?? null,
        numero: (a as any).numero ?? null,
        pages: (a as any).pages ?? null,
        fichierUrl: (a as any).fichierUrl ?? null,
        doi: `10.1234/nihary.${slug.slice(0, 30)}`,
        auteurId,
      },
    });
    count++;
  }

  console.log(`   ✅ Articles revue créés : ${count}`);
}
