"use client";
import { FileCheck2, ImageIcon, Scale, Upload } from "lucide-react";

export type UploadedEvidence = { auteurs: string; thumbnailUrl: string; cvUrl: string; contentUrl: string; contentName: string; contentMime: string; declarationAcceptedAt: string; declarationVersion: string };
export async function uploadSubmissionEvidence(form: HTMLFormElement): Promise<UploadedEvidence> { const response = await fetch("/api/uploads/submission", { method: "POST", body: new FormData(form) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "Téléversement impossible"); return result.evidence; }

export default function SubmissionEvidenceFields({ contentLabel = "Document ou média principal", contentAccept = ".pdf,.doc,.docx,.txt,image/*,audio/*,video/*" }: { contentLabel?: string; contentAccept?: string }) {
  return <section className="card-sable space-y-5 p-5 sm:p-6"><div><span className="eyebrow">Dossier obligatoire</span><h2 className="mt-1 font-display text-xl font-semibold">Fichiers, identité et droits</h2><p className="mt-2 text-sm leading-6 text-nihary-gris">Ces éléments permettent de vérifier l’auteur, préparer la publication et prévenir toute usurpation d’identité.</p></div><label className="block text-sm font-medium">Nom complet de chaque auteur·rice *<input name="submissionAuthors" className="input mt-1" required minLength={3} placeholder="Prénom Nom — Institution; co-auteur·rice…" /></label><div className="grid gap-4 sm:grid-cols-2"><FileInput name="submissionThumbnail" label="Miniature *" help="JPG, PNG ou WebP · 5 Mo max." accept="image/jpeg,image/png,image/webp" icon={ImageIcon} /><FileInput name="submissionCv" label="CV de la personne *" help="PDF uniquement · 10 Mo max." accept="application/pdf" icon={FileCheck2} /></div><FileInput name="submissionContent" label={`${contentLabel} *`} help="PDF, document, texte, image, audio ou vidéo · 50 Mo max." accept={contentAccept} icon={Upload} /><label className="flex items-start gap-3 rounded-lg border border-nihary-or/30 bg-white p-4 text-sm leading-6"><input name="submissionDeclaration" type="checkbox" value="accepted" required className="mt-1 h-4 w-4 shrink-0 accent-nihary-or" /><span><Scale className="mr-1 inline text-nihary-or" size={16} /><strong>Déclaration sur l’honneur *</strong><br />Je certifie être l’auteur·rice, le représentant autorisé ou disposer de toutes les permissions nécessaires. Je garantis l’exactitude des identités indiquées et reconnais être responsable en cas de plagiat, violation de droits ou usurpation d’identité.</span></label></section>;
}
function FileInput({ name, label, help, accept, icon: Icon }: { name: string; label: string; help: string; accept: string; icon: typeof Upload }) { return <label className="block rounded-lg border border-dashed border-nihary-or/50 bg-white p-4 text-sm font-medium"><span className="flex items-center gap-2"><Icon className="text-nihary-or" size={18} />{label}</span><input name={name} type="file" required accept={accept} className="mt-3 block w-full text-xs file:mr-3 file:rounded-md file:border-0 file:bg-nihary-sable file:px-3 file:py-2 file:text-nihary-brun" /><span className="mt-2 block text-xs font-normal text-nihary-gris">{help}</span></label>; }
