import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, BriefcaseBusiness, CalendarDays, CheckCircle2, Clock3, GraduationCap, Mail, MapPin, WalletCards } from "lucide-react";
import { getOffre, offres, OFFRE_TYPE_LABELS } from "@/lib/offres";

export function generateStaticParams() { return offres.map((offre) => ({ slug: offre.slug })); }
export function generateMetadata({ params }: { params: { slug: string } }) { const offre = getOffre(params.slug); return offre ? { title: `${offre.titre} | Offres FINIDY`, description: offre.resume } : {}; }
const info = (label: string, value: string, Icon: typeof MapPin) => <div className="flex gap-3"><Icon className="mt-0.5 shrink-0 text-nihary-or" size={18} /><div><dt className="text-xs uppercase tracking-wide text-nihary-gris">{label}</dt><dd className="mt-0.5 text-sm font-medium">{value || "N/A"}</dd></div></div>;

export default function OffrePage({ params }: { params: { slug: string } }) {
  const offre = getOffre(params.slug); if (!offre) notFound();
  const similaires = offres.filter((item) => item.slug !== offre.slug && (item.type === offre.type || item.domaine === offre.domaine)).slice(0, 3);
  return <main><section className="border-b border-nihary-sable-fonce bg-nihary-gradient"><div className="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8"><Link href="/consultance/offres" className="mb-7 inline-flex items-center gap-2 text-sm text-nihary-gris hover:text-nihary-or"><ArrowLeft size={15} />Toutes les offres</Link><div className="grid gap-8 lg:grid-cols-[1fr_320px] lg:items-end"><div><div className="flex flex-wrap gap-2"><span className="badge">{OFFRE_TYPE_LABELS[offre.type]}</span><span className="badge-libre">Candidatures ouvertes</span></div><h1 className="mt-4 max-w-4xl font-display text-4xl font-bold leading-tight sm:text-5xl">{offre.titre}</h1><p className="mt-3 text-lg font-medium text-nihary-brun">{offre.organisation}</p><p className="mt-5 max-w-3xl text-base leading-7 text-nihary-gris">{offre.resume}</p></div><div className="card overflow-hidden"><div className="relative h-40"><Image src={offre.image} alt="" fill className="object-cover" sizes="320px" /></div><div className="p-5"><p className="text-xs text-nihary-gris">Date limite de candidature</p><p className="mt-1 font-display text-xl font-semibold">{new Date(offre.dateLimite).toLocaleDateString("fr-FR", { day: "numeric", month: "long", year: "numeric" })}</p><a href={`mailto:${offre.contact}?subject=Candidature — ${offre.titre}`} className="btn-primary mt-5 w-full justify-center"><Mail size={15} />Postuler</a></div></div></div></div></section>
    <div className="mx-auto grid max-w-7xl gap-8 px-4 py-12 sm:px-6 lg:grid-cols-[1fr_340px] lg:px-8"><article className="space-y-9"><section><span className="eyebrow">L’opportunité</span><h2 className="mt-1 text-2xl font-semibold">Description</h2><p className="mt-4 leading-8 text-nihary-brun">{offre.description}</p></section><Detail title="Missions principales" items={offre.missions} /><Detail title="Profil recherché" items={offre.profil} /><section><h2 className="text-2xl font-semibold">Compétences clés</h2><div className="mt-4 flex flex-wrap gap-2">{offre.competences.map((item) => <span className="badge" key={item}>{item}</span>)}</div></section><Detail title="Ce que l’opportunité propose" items={offre.avantages.length ? offre.avantages : ["N/A"]} /><Detail title="Dossier de candidature" items={offre.candidature.length ? offre.candidature : ["N/A"]} /><div className="card-sable p-6"><h2 className="font-display text-xl font-semibold">Comment candidater ?</h2><p className="mt-2 text-sm leading-6 text-nihary-gris">Envoyez les pièces demandées à <a className="font-medium text-nihary-or hover:underline" href={`mailto:${offre.contact}`}>{offre.contact}</a> en indiquant le titre exact de l’offre dans l’objet.</p></div></article><aside><div className="card sticky top-28 p-6"><h2 className="font-display text-xl font-semibold">Informations clés</h2><dl className="mt-6 space-y-5">{info("Lieu", offre.lieu, MapPin)}{info("Mode", offre.mode, BriefcaseBusiness)}{info("Type de contrat", offre.contrat, BriefcaseBusiness)}{info("Durée", offre.duree, Clock3)}{info("Temps de travail", offre.tempsTravail, Clock3)}{info("Rémunération / montant", offre.remuneration, WalletCards)}{info("Niveau d’études", offre.niveauEtudes, GraduationCap)}{info("Expérience", offre.experience, CheckCircle2)}{info("Financement", offre.financement, WalletCards)}{info("Prise de fonction", offre.debut, CalendarDays)}{info("Langues", offre.langues, BriefcaseBusiness)}</dl><div className="mt-6 border-t border-nihary-sable-fonce pt-5 text-xs text-nihary-gris">Publiée le {new Date(offre.datePublication).toLocaleDateString("fr-FR")}</div></div></aside></div>
    {similaires.length > 0 && <section className="border-t border-nihary-sable-fonce bg-white"><div className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8"><span className="eyebrow">À découvrir aussi</span><h2 className="mt-1 text-2xl font-semibold">Opportunités similaires</h2><div className="mt-6 grid gap-4 md:grid-cols-3">{similaires.map((item) => <Link href={`/consultance/offres/${item.slug}`} className="card p-5 hover:border-nihary-or" key={item.slug}><span className="badge">{OFFRE_TYPE_LABELS[item.type]}</span><h3 className="mt-3 font-display text-lg font-semibold">{item.titre}</h3><p className="mt-2 text-sm text-nihary-gris">{item.organisation} · {item.lieu}</p></Link>)}</div></div></section>}
  </main>;
}

function Detail({ title, items }: { title: string; items: string[] }) { return <section><h2 className="text-2xl font-semibold">{title}</h2><ul className="mt-4 space-y-3">{items.map((item) => <li className="flex gap-3 leading-7 text-nihary-brun" key={item}><CheckCircle2 className="mt-1.5 shrink-0 text-nihary-or" size={17} />{item}</li>)}</ul></section>; }
