"use client";
import { useMemo, useState } from "react";
import { Search, Users } from "lucide-react";

type Item={id:string;type:"contact"|"consultance"|"commande";nom:string;email:string;sujet:string;detail:string;statut:string;notes:string|null;createdAt:string};
type Analytics={totalUsers:number;verified:number;complete:number;authors:number;experts:number;newThisMonth:number;roles:Array<{role:string;count:number}>};
const STATUS={contact:["NOUVEAU","EN_COURS","EN_ATTENTE","RESOLU","ARCHIVE"],consultance:["EN_ATTENTE","EN_COURS","CLOTURE"],commande:["NOUVELLE","CONFIRMEE","EN_PREPARATION","EXPEDIEE","LIVREE","ANNULEE"]};

export default function CrmBoard({initialItems,analytics}:{initialItems:Item[];analytics:Analytics}){
  const[items,setItems]=useState(initialItems),[filter,setFilter]=useState("TOUS"),[query,setQuery]=useState(""),[error,setError]=useState("");
  const shown=useMemo(()=>items.filter(i=>(filter==="TOUS"||i.type===filter)&&`${i.nom} ${i.email} ${i.sujet} ${i.detail}`.toLowerCase().includes(query.toLowerCase())),[items,filter,query]);
  async function update(item:Item,statut:string,notes=item.notes||""){const response=await fetch("/api/admin/crm",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:item.id,type:item.type,statut,notes})});const data=await response.json();if(!response.ok){setError(data.error);return}setItems(rows=>rows.map(row=>row.id===item.id&&row.type===item.type?{...row,statut,notes}:row))}
  const completion=analytics.totalUsers?Math.round(analytics.complete/analytics.totalUsers*100):0,verification=analytics.totalUsers?Math.round(analytics.verified/analytics.totalUsers*100):0;
  const metrics=[["Utilisateurs",analytics.totalUsers,`+${analytics.newThisMonth} ce mois`],["Profils complets",`${completion}%`,`${analytics.complete} dossiers`],["Comptes vérifiés",`${verification}%`,`${analytics.verified} membres`],["Auteurs",analytics.authors,"profils éditoriaux"],["Experts",analytics.experts,"consultance & formation"]];
  return <div className="space-y-8"><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{metrics.map(([label,value,detail])=><div className="card p-5" key={String(label)}><Users className="mb-3 text-nihary-or" size={20}/><p className="text-xs uppercase tracking-wider text-nihary-gris">{String(label)}</p><p className="mt-1 font-display text-3xl font-bold text-nihary-ambre-fonce">{String(value)}</p><p className="mt-1 text-xs text-nihary-gris">{String(detail)}</p></div>)}</section><section className="card p-6"><div className="flex h-40 items-end gap-3">{analytics.roles.map(r=>{const h=Math.max(12,Math.round(r.count/Math.max(...analytics.roles.map(x=>x.count),1)*120));return <div key={r.role} className="flex flex-1 flex-col items-center"><span className="mb-1 text-xs font-medium">{r.count}</span><div className="w-full rounded-t bg-nihary-or" style={{height:h}}/><span className="mt-2 text-[10px] text-nihary-gris">{r.role}</span></div>})}</div></section><section><div className="mb-5 flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div className="flex flex-wrap gap-2">{[["TOUS","Tout"],["contact","Messages"],["consultance","Consultance"],["commande","Commandes papier"]].map(([v,l])=><button key={v} className={filter===v?"btn-primary":"btn-outline"} onClick={()=>setFilter(v)}>{l}</button>)}</div><label className="relative"><Search className="absolute left-3 top-3 text-nihary-gris" size={16}/><input className="input pl-9" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rechercher dans le CRM…"/></label></div>{error&&<p className="mb-3 text-red-700">{error}</p>}<div className="grid gap-4 xl:grid-cols-2">{shown.map(item=><article key={`${item.type}-${item.id}`} className="card p-5"><div className="flex justify-between gap-3"><div><span className="badge">{item.type}</span><h2 className="mt-2 font-semibold">{item.sujet}</h2><p className="text-sm">{item.nom} · <a href={`mailto:${item.email}`} className="text-nihary-or">{item.email}</a></p></div><select className="input h-fit !w-auto" value={item.statut} onChange={e=>void update(item,e.target.value)}>{STATUS[item.type].map(s=><option key={s}>{s}</option>)}</select></div><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-nihary-gris">{item.detail}</p><textarea className="input mt-4 min-h-20" defaultValue={item.notes||""} placeholder="Notes internes…" onBlur={e=>void update(item,item.statut,e.target.value)}/><p className="mt-2 text-[11px] text-nihary-gris">{new Date(item.createdAt).toLocaleString("fr-FR")}</p></article>)}</div></section></div>;
}
