"use client";
import { FormEvent, useState } from "react";
import { Pencil, Plus, X } from "lucide-react";
type Item={id:string;titre:string;organisation:string;type:string;statut:string;payload:Record<string,string>};
const empty={titre:"",organisation:"",type:"EMPLOI",domaine:"",lieu:"",mode:"Présentiel",dateLimite:"",image:"",resume:"",description:"",contrat:"",remuneration:"",contact:"",statut:"BROUILLON"};
export default function OffersManager({initialItems}:{initialItems:Item[]}){
 const[items,setItems]=useState(initialItems),[form,setForm]=useState(empty),[editId,setEditId]=useState<string|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(false);
 async function save(event:FormEvent){event.preventDefault();setLoading(true);setError("");const response=await fetch("/api/admin/offres",{method:editId?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(editId?{id:editId,...form}:form)});const data=await response.json();if(response.ok){setItems(current=>editId?current.map(row=>row.id===editId?data.item:row):[data.item,...current]);reset()}else setError(data.error);setLoading(false)}
 async function status(item:Item,value:string){const response=await fetch("/api/admin/offres",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:item.id,statut:value})});const data=await response.json();if(response.ok)setItems(current=>current.map(row=>row.id===item.id?data.item:row));else setError(data.error)}
 function edit(item:Item){setEditId(item.id);setForm({...empty,titre:item.titre,organisation:item.organisation,type:item.type,statut:item.statut,domaine:item.payload.domaine||"",lieu:item.payload.lieu||"",mode:item.payload.mode||"Présentiel",dateLimite:item.payload.dateLimite||"",image:item.payload.image||"",resume:item.payload.resume||"",description:item.payload.description||"",contrat:item.payload.contrat||"",remuneration:item.payload.remuneration||"",contact:item.payload.contact||""});window.scrollTo({top:0,behavior:"smooth"})}
 function reset(){setForm(empty);setEditId(null)}
 const field=(key:keyof typeof empty,label:string,required=false)=><label className="block text-sm font-medium">{label}{required&&" *"}<input className="input mt-1" required={required} value={form[key]} onChange={event=>setForm({...form,[key]:event.target.value})}/></label>;
 return <div className="grid gap-8 lg:grid-cols-[.9fr_1.1fr]"><form onSubmit={save} className="card h-fit space-y-4 p-6"><div className="flex items-start justify-between"><div><span className="eyebrow">{editId?"Modification":"Nouvelle opportunité"}</span><h2 className="mt-1 text-xl font-semibold">{editId?"Mettre à jour l’offre":"Ajouter une offre"}</h2></div>{editId&&<button type="button" className="btn-ghost !p-2" onClick={reset} aria-label="Annuler la modification"><X size={17}/></button>}</div>{field("titre","Intitulé",true)}{field("organisation","Organisation",true)}<div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Type<select className="input mt-1" value={form.type} onChange={event=>setForm({...form,type:event.target.value})}><option>EMPLOI</option><option>STAGE</option><option>BOURSE</option><option>CONTRAT_DOCTORAL</option><option>MISSION_TERRAIN</option></select></label>{field("domaine","Domaine",true)}{field("lieu","Lieu",true)}{field("dateLimite","Date limite",true)}</div>{field("image","URL de la miniature")}<label className="block text-sm font-medium">Résumé *<textarea className="input mt-1 min-h-20" required value={form.resume} onChange={event=>setForm({...form,resume:event.target.value})}/></label><label className="block text-sm font-medium">Description *<textarea className="input mt-1 min-h-32" required value={form.description} onChange={event=>setForm({...form,description:event.target.value})}/></label><div className="grid gap-4 sm:grid-cols-2">{field("contrat","Contrat")}{field("remuneration","Rémunération")}</div>{field("contact","Contact",true)}{error&&<p className="text-sm text-red-700">{error}</p>}<button className="btn-primary w-full justify-center" disabled={loading}>{editId?<Pencil size={15}/>:<Plus size={15}/>} {loading?"Enregistrement…":editId?"Enregistrer les modifications":"Créer l’offre"}</button></form><section><h2 className="mb-4 text-xl font-semibold">Offres administrables</h2><div className="space-y-3">{items.map(item=><article className="card p-5" key={item.id}><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><span className="badge">{item.type}</span><h3 className="mt-2 font-display font-semibold">{item.titre}</h3><p className="text-xs text-nihary-gris">{item.organisation}</p></div><div className="flex gap-2"><button className="btn-ghost !px-3" onClick={()=>edit(item)}><Pencil size={14}/>Modifier</button><select className="input !w-auto" value={item.statut} onChange={event=>void status(item,event.target.value)}><option>BROUILLON</option><option>PUBLIE</option><option>ARCHIVE</option></select></div></div><p className="mt-3 line-clamp-2 text-sm text-nihary-gris">{item.payload.resume}</p></article>)}</div></section></div>;
}
