"use client";

import { CheckCircle2, PackageCheck, Send } from "lucide-react";
import { FormEvent, useState } from "react";

export default function PrintOrderForm({ typeProduit, referenceId, titreProduit }: { typeProduit: "REVUE" | "MAGAZINE"; referenceId?: string; titreProduit: string }) {
  const [form, setForm] = useState({ format: "DOS_CARRE", quantite: "1", nomClient: "", emailClient: "", telephone: "", adresse: "", ville: "", pays: "Madagascar", notes: "" });
  const [loading, setLoading] = useState(false); const [done, setDone] = useState(false); const [error, setError] = useState("");
  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setError(""); const response = await fetch("/api/commandes-papier", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, quantite: Number(form.quantite), typeProduit, referenceId, titreProduit }) }); const data = await response.json(); if (response.ok) setDone(true); else setError(data.error || "Commande impossible"); setLoading(false); }
  if (done) return <div className="card p-10 text-center"><CheckCircle2 className="mx-auto mb-4 text-emerald-600" size={46} /><h2 className="font-display text-2xl font-semibold text-nihary-ambre-fonce">Demande de commande reçue</h2><p className="mx-auto mt-2 max-w-lg text-sm leading-6 text-nihary-gris">L’équipe FINIDY vous contactera pour confirmer le prix, la disponibilité, la livraison et le paiement.</p></div>;
  const field = (key: keyof typeof form, label: string, type = "text", required = true) => <label className="block text-sm font-medium text-nihary-brun">{label}{required && " *"}<input className="input mt-1" type={type} required={required} value={form[key]} onChange={(e) => setForm({ ...form, [key]: e.target.value })} /></label>;
  return <form onSubmit={submit} className="card p-6 sm:p-8"><div className="mb-6 flex items-start gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-lg bg-nihary-or-pale text-nihary-ambre"><PackageCheck size={20} /></span><div><p className="text-xs uppercase tracking-wider text-nihary-or">Édition imprimée</p><h2 className="font-display text-xl font-semibold text-nihary-ambre-fonce">{titreProduit}</h2></div></div><div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm font-medium text-nihary-brun">Finition *<select className="input mt-1" value={form.format} onChange={(e) => setForm({ ...form, format: e.target.value })}><option value="DOS_CARRE">Dos carré collé</option><option value="LIVRE_RELIE">Livre relié</option></select></label>{field("quantite", "Quantité", "number")}{field("nomClient", "Nom complet")}{field("emailClient", "E-mail", "email")}{field("telephone", "Téléphone")}{field("ville", "Ville")}{field("pays", "Pays")}</div><label className="mt-4 block text-sm font-medium text-nihary-brun">Adresse de livraison *<textarea className="input mt-1 min-h-24" required value={form.adresse} onChange={(e) => setForm({ ...form, adresse: e.target.value })} /></label><label className="mt-4 block text-sm font-medium text-nihary-brun">Précisions<textarea className="input mt-1 min-h-20" value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} /></label><p className="mt-4 text-xs leading-5 text-nihary-gris">Cette demande ne déclenche aucun paiement. Le prix final dépend de la finition, du tirage et de la destination.</p>{error && <p className="mt-3 text-sm text-red-700">{error}</p>}<button disabled={loading} className="btn-primary mt-5 w-full justify-center"><Send size={15} />{loading ? "Envoi…" : "Demander une commande"}</button></form>;
}
